### ISSUE TITLE
ArrayProxy missing from phosphor.core

### ISSUE THREAD

**Issue by drglitch** [phosphorjs/phosphor-core#1]
PhosphorUI examples require phosphor.core.arrayproxy.ArrayProxy which appears to be missing from dist and src

**Comment by sccolbert** [comment]
Yeah, I'm about to make a big merge from feature-visibility that will correct that. Things are still changing rapidly, so bear with me :)

**Comment by drglitch** [comment]
:+1:

**Comment by sccolbert** [comment]
Fixed in version phosphor-core `0.0.24` and phosphor-ui `0.0.15`
